version: 2

python:
  version: "3.8"
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      extra_requirements:
        - requirements.txt

sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub
